# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b1626b3ce53aed1724297a226bf19b87f68ae990146066ef2517167817e5eb8644ed46974462c5f70460af76f540fc8bb381a5040d0eb5b99d067f3a88cce19

test:
  secret_key_base: e35cb6005d79aa2911047dc16493a56bf0d187240a58487728686ac5fcc7ce18c2c6979e5d2185847afe45e8ff67d1068a3a4feab9eab0389f6bb30e31d767aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
